name: Continuous delivery

on:
  release:
    types: [published]

jobs:
  publish_to_docker_hub:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Download release
        uses: robinraju/release-downloader@v1.7
        with:
          tag: ${{github.event.release.tag_name}}
          tarBall: true
      - name: Unpack release
        run: tar -xzf ./${{github.event.repository.name}}-${{github.event.release.tag_name}}.tar.gz
      - name: Remove tarball
        run: rm ./${{github.event.repository.name}}-${{github.event.release.tag_name}}.tar.gz
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/${{github.event.repository.name}}:${{github.event.release.tag_name}}
