name: Continuous integration

on:
  push:
  pull_request:

env:
  NODE_VERSION: 22.2.0

jobs:
  build_docker_image:
    name: Build a Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build a Docker image
        run: |
          docker build --tag=${{github.repository}}:${{github.sha}} --file=Dockerfile --build-arg="NODE_VERSION=${{env.NODE_VERSION}}" .
  compile_check:
    name: Compile check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
      - name: Install dependencies
        run: |
          npm ci
      - name: Run compile check
        run: |
          npm run compile:check
  eslint_check:
    name: ESLint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
      - name: Install dependencies
        run: |
          npm ci
      - name: Run ESLint
        run: |
          npm run eslint:check
  hadolint_check:
    name: Hadolint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  prettier_check:
    name: Prettier check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
      - name: Install dependencies
        run: |
          npm ci
      - name: Run prettier
        run: |
          npm run prettier:check
  nodejs_test:
    name: Node.js test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "npm"
      - name: Install dependencies
        run: |
          npm ci
      - name: Run Node.js test runner
        run: |
          npm run test
